### ISSUE TITLE
Target types: scope vs conformance

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#123]
According to the scope clause:

> The target of the conformance classes specified in this document are
> 
> * CityGML encoding specifications that provide encodings for the UML data model specified in this document, and 
> * Additional UML models that can be created by users to extend this data model as Application Domain Extensions. 

According to the conformance clause:

> The Standardization Targets for this standard are Implementation Specifications.

It seems that it is the scope that is wrong, and the text in the second bullet should be removed.

In addition, the same terminology should be applied in the whole document, so "encoding specification" → "implementation specification".

**Comment by heidivanparys** [comment]
> It seems that it is the scope that is wrong, and the text in the second bullet should be removed.

After checking chapter 10, that actually does not seem to be the case. Because chapter 10 specifies requirements and recommendations for Application Domain Extensions. According to the URI structure, those requirements and recommendation belong to the Core requirements class. But shouldn't these requirements and recommendations from chapter 10 be grouped in a separate requirements class? And associated to that, a conformance class? As they have a different standardization target? implementation specification vs. conceptual model that is an extension of the CityGML model?

If the above is true, then the conformance clause should be updated. And the structure of the requirements classes and conformance classes should too, etc.

**Comment by TatjanaKutzner** [comment]
Yes, the conformance clause needs to be updated to include ADEs as well.

The requirements and recommendations should be grouped in a separate requirements class. It's somehow confusing that the requirement on Generics classes belongs to the Core requirements class.

**Comment by cmheazel** [comment]
A common use of Conformance Classes is to inform the user about which optional parts of a Standard are supported. One mandatory Conformance Class (Core) and everything else is optional. Therefore, if extensions (Generics, ADEs, etc.) are mandatory, then they should be in the Core Conformance Class. Otherwise we have multiple mandatory Conformance Classes which may be a bit strange.

**Comment by 3DXScape** [comment]
Chuck knows what to do(?!). Generics and ADEs become optional. Implementation target for ADEs UML models.

**Comment by cmheazel** [comment]
Generics is now a separate, optional class.
ADEs are now a separate, optional class.
Each package has a requirement that ADE elements and properties cannot be used unless conformance with the ADE Conformance Class is demonstrated.
Chapter 10 now only deals with ADEs and the ADE Conformance Class
Extensions are discussed in section 7.7
Generics and ADEs are no-longer required to be conformant with Core.

**Comment by clausnagel** [comment]
I think it's a pitty that the text in chapter 10 is simply cut to ADEs. It had a good disucssion about pros and cons of generic attributes and also about code lists, both of which is lost now. This previous content could be integrated into chapter 7, but for me this does not feel right because chapter 7 should just provide an overview. Actually, I liked it that there was one place to read about CityGML extension possibilities.

**Comment by cmheazel** [comment]
@clausnagel I agree, and spent some time struggling with it. But if ADEs are a conformance class, then they deserve their own section. I'm open to any ideas on how to bring the other content back.  Perhaps a separate section (or subsection) dedicated to extensions?  Or perhaps a section in the Users Guide?

**Comment by cmheazel** [comment]
The June 23 Editors Meeting decided that we should create an informative Extensions section. The content deleted from Section 10 will re-appear there.
The Extensions section is targeted for the Users Guide, but it will be written so that is can be inserted into the standard if that's what the SWG decides.
See also #141

**Comment by cmheazel** [comment]
ToDo: explore how to support multiple standardization targets (derived conceptual models as well as implementation specifications) then update the spec to make this distinction.
Note: this may drive us to two Abstract Test Suites.

**Comment by 3DXScape** [comment]
Next step to resolution is review spec to make certain standardization target (extended model or implementation) is everywhere unambiguous. Agreed during 6th August editors meeting by unanimous consent.

**Comment by 3DXScape** [comment]
Includes possibility that there may be multiple targets.

**Comment by 3DXScape** [comment]
CH - still in process.

**Comment by cmheazel** [comment]
Proposition: Only the ADE Requirements Class applies to conceptual model profiles. This is the only case where new classes would be created. Therefore, the ADE Requirements Class is the only one which has a Conceptual Model standardization target.
The current version of the standard reflects this proposition.

**Comment by 3DXScape** [comment]
We had discussion of how ADE schemata could be conformance tested and decided that it was outside our current scope but an important issue for consideration in the right venue. Agreed by unanimous consent, closed 3 Sept meeting
