### ISSUE TITLE
ISO19107

### ISSUE THREAD

**Issue by Chika96** [opengeospatial/CityGML-3.0CM#125]
The latest edition of the Spatial Schema is ISO 19107:2019 but the conceptual model refers to ISO 19107:2003. If possible, it's better to apply the latest one.

**Comment by TatjanaKutzner** [comment]
I think that requires more than just the "Draft Review Editorial Typo-Grammar" label.

We started the development of City GML 3.0 a long time before the new version of ISO 19107 was released. 
When now referring to ISO 19107:2019 this would also mean that we have to import the new ISO 19107 UML model in the EAP project and modify all UML diagrams, because the new version does not use the prefix `GM_` any more for the class names.

Or can we simply refer to the new version without adapting all UML diagrams?

**Comment by 3DXScape** [comment]
I changed the category label to reflect the level of response required.

**Comment by 3DXScape** [comment]
Use 2003 but explain in spec

**Comment by TatjanaKutzner** [comment]
Yes, we should stick to the version from 2003 and explain in the specification why we use this version. For the new version we don't know what things have changed and we also don't know if software tools are already able to deal with the new version.

**Comment by PeterParslow** [comment]
I agree with Tatjana, but warn that this might get some push back, as work on ISO 19107:2019 was initiated from OGC (John Herring). 

That said, it is a major rewrite of the standard, with a very different-looking UML model. Also, a number of issues have been reported against the 19107:2019 model as it starts being used: see http://isotc211.standardstracker.org/requestlist.cgi?component=ISO%2019107%3A2019&list_id=1315&product=ISO%2FTC%20211&resolution=---

**Comment by cmheazel** [comment]
Agreed to close at the SWG meeting of 20 August 2020
