### ISSUE TITLE
Metadata and CityGML Conceptual Model

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#141]
The CM document under review is presently agnostic of metadata (meaning here consistent with ISO 19115 standards or any other metadata standard), as it contains neither requirement(s) nor statement about metadata. 
However it contains in Chapter 4 References the ISO 19115-1:2014 normative reference.
This reference should be either suppressed, or some statement be added that metadata is implicit in the CityGML data model, and may apply on basis of the general ISO TC211 for developing application schemas. 
Or at minimum in the introduction of this CM document, clarify why metadata is not addressed in the CM standard.

**Comment by EmDevys** [comment]
A side comment on this is about compatibility with CityGML 2.0 standard (which was a 2 in 1 (CM + GML encoding) which includes some statements on metadata.

**Comment by TatjanaKutzner** [comment]
ISO 19115 is listed in Chapter 4, because it was already listed in the CityGML 2.0 standard.
In addition, in the CityGML 2.0 standard also ISO 19139 was listed, since _CityModel and _Feature inherited the gml:metaDataProperty property in the GML encoding which allows then to add metadata from ISO 19115/19139.
The reference to ISO 19139 was removed in the CityGML 3.0 document, because it defines a conceptual model only.

Since the conceptual model does not make use of ISO 19115, I would also suggest to suppress the reference in the document and provide some information in the introduction that metadata is not addressed in this CM standard, however, that encodings that support metadata are free to make use of the relevant standards.

**Comment by 3DXScape** [comment]
Since the conceptual model does not make use of ISO 19115, I would also suggest to suppress the reference in the document and provide some information in the introduction that metadata is not addressed in this CM standard, however, that encodings that support metadata are free to make use of the relevant standards. 

Also explain how metadata could be encoded in CityGML 3 via generics or ADE. 

Tatjana will implement.

**Comment by cmheazel** [comment]
References to ISO 19115 have been removed.

**Comment by PeterParslow** [comment]
Sorry I didn't say earlier. I would prefer a simple reference to metadata, perhaps (for now) just from the CityModel. The implementation of that may be encoding-dependent, e.g. that GML should use a property that inherits from gml:AbstractMetadataPropertyType (we can just use the gml:metadataProperty but that is deprecated in 3.2)

That said, I wouldn't hold up public review to resolve this question. I'm largely thinking of 'defending' CityGML from the criticism that it doesn't handle metadata.

**Comment by cmheazel** [comment]
The June 23 Editors Meeting decided that we should create an informative Extensions section. A discussion of metadata could be added to this new section. 
The Extensions section is targeted for the Users Guide, but it will be written so that is can be inserted into the standard is that's what the SWG decides.

**Comment by cmheazel** [comment]
This is not a simple issue.
CityGML is Feature data. The line between Metadata and Feature data is thin at best. A query may be directed against the Feature data, against a separate metadata store, or some hybrid of the two. 
Then there is the question of what the metadata describes. The entire dataset?  A package? Individual features? Any and all of these answers can be correct.
I suggest we describe how the extension capabilities can be used to add metadata, but leave the details to the implementation specifications.

**Comment by 3DXScape** [comment]
Metadata can be incorporated via ADE mechanism or using generic attributes. This enables precise definition of application or domain-specific properties. There is also an opportunity for using native metadata mechanisms provided by specific encodings in implementation specifications. This information will appear in the User Guide. Agreed 6.8.20 with the reservation that we are prioritizing addressing metadata out of the conceptual model specification and relying on a hypothetical ADE for metadata support. Should revisit for versions 3.X.

**Comment by cmheazel** [comment]
Status August 7, 2020 - a metadata section has been added to the users guide. The "Extending CityGML" section of the Overview references the Users Guide, but doesn't explicitly discuss metadata. Is this sufficient?

**Comment by 3DXScape** [comment]
Need to add to auto-generated Users Guide doc.

**Comment by 3DXScape** [comment]
Agreed to close at 20 August SWG meeting.
