### ISSUE TITLE
Redlines from Carl Reed

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#161]
Carl Reed submitted a Word version of the draft standard with change bars to indicate recommended changes as well as embedded comments. This issue captures the issues which require more thought than a simple change in sentence structure.

- [x] Introduction: last sentence - Does the model enable this exchange or does some encoding (JSON, XML, etc) based on the model enable the encoding? There is some confusion perhaps between the model and implementation standards based on the model. This distinction (if any) is not clear to me.

- [x] Scope: second sentence - What I just suggested above  Perhaps some words such as these should be in the abstract so that the reader is very clear about what is implementable and what is not?

- [x] Global - replace Conceptual Model with CM.

- [x] Global - replace encoding specifications with encoding standards

- [x] Scope: list of implementation specifications in paragraph 6 - Only COLLADA is shown in the references. These other documents should also be given in the Normative References

- [x] Section 3.3 last paragraph - change defined to documented.

- [x] Section 6.3 - Sorry, but this whole section is confusing and I believe unnecessary. Yes, a short paragraph defining the universe of discourse for this standard is appropriate. Also, much of the content in this section also repeats what has been provided in previous sections.

- [x] Section 7 - Should this entire section – of great information – actually be a separate document titled something like “Introduction to the CityGML 3.0 Conceptual Model”?

**Comment by cmheazel** [comment]
Replace Conceptual Model with CM - elected not to make this change. The fact that this is a standard for a Conceptual Model is central to understanding CityGML. So replication of this term is valuable. In addition, CM is not a particularly memorable nor unique abbreviation.,
Also - we use upper case to distinguish between Conceptual Model when used as the title of this standard vs. conceptual model as in the concept.

**Comment by cmheazel** [comment]
Replace encoding specifications with encoding standards - The term registered in the OGC Document Types Register is Implementation Specification. So that is the term we should use.

**Comment by cmheazel** [comment]
Section 3.3 last paragraph - The Conceptual Model is **defined** by the UML model. The CityGML document is a representation of that model.  So defined is the proper term.
Since the UML is the Conceptual Model, then it is the authoritative definition of that model. All other representations are subordinate.

**Comment by cmheazel** [comment]
Section 6.3 - I think we can delete this whole section. Any objections?

**Comment by 3DXScape** [comment]
What is "this section"? If 3.3 then I agree.

**Comment by 3DXScape** [comment]
I mean 6.3 sorry for confusion.

**Comment by TatjanaKutzner** [comment]
I also agree that we can delete section 6.3.

But: since someone wrote this whole text (I think Chuck), I would suggest to move it to the User Guide for the moment, so that it doesn't get lost completely. And then we can still decide there, whether we prefer to keep or delete.

**Comment by TatjanaKutzner** [comment]
Section 3.3 last paragraph:
In my understanding, the sentence "the Conceptual Model is **defined** by the UML model" somehow implies that the UML model **describes** the Conceptual Model, but not that the UML model **is** the Conceptual Model.
I would rather favour "the Conceptual Model is **represented** by the UML model", in this way, according to my understanding, both, the conceptual model and the UML model, are equivalent.

**Comment by 3DXScape** [comment]
How about "The Conceptual Model is defined as a UML class diagram." To me this makes it clear that the UML is the method used to record the model and this recoding *is* the model. The original sentence also works for me but is a tiny bit less clear as to the status of the UML model versus some hypothetical other expression of the "real" Conceptual Model. It mostly depends on the preposition choice: "as" versus "by". "as" denotes equivalence or identity while "by" might mean a projection or description (or equivalence).

**Comment by cmheazel** [comment]
@3DXScape A diagram is not a model. What we are trying to say is that there is a mathematical construct which captures all of the concepts and associations which are CityGML. This construct is far too complex to be captured in two dimensions. Diagrams and data dictionaries provide views into the model. But those views are just a tiny fraction of the whole. So the CityGML Conceptual Model is a distinct mathematical construct. The CityGML Conceptual Model Standard provides views into the model and instruction on how to use it.

**Comment by 3DXScape** [comment]
When I say diagram, I don't mean graphics. A graphical expression of a model is not a model but the data defining class diagrams does define a model, constrained by the expressiveness of the meta-schema, in this case the UML metamodel. So isn't that the definitive mathematical construct? And the data in the EA project or XMI files or extracted via a template are  expressions of that model?

**Comment by cmheazel** [comment]
@3DXScape It's a bit of a sore point with me. I've dealt with far too many UML "models" done in Powerpoint. And they are uniformly bad. So I don't even want to mention the word "diagram" in the same context as model.

**Comment by 3DXScape** [comment]
I totally understand. I think the official name of the thing defined by the UML is "static class diagram". This is in the spirit of, for example, Feynman Diagram, though.

**Comment by cmheazel** [comment]
@3DXScape Please take a look at issue #163. It occurred to me that we may be re-inventing the wheel. If we anchor CityGML in Model Driven Architecture (MDA), then we have a set of international standards and conventions to draw on.  For example, the MDA distinction between a Platform Independent Model (PIM) and Platform Specific Model (PSM) is well documented. So we simply assert:
    Conceptual Model == PIM
    Implementation Specifications == PSM

This will require some re-writing of the non-normative parts of the standard, but I think it would be worth it.

**Comment by TatjanaKutzner** [comment]
Coming back to "as" versus "by", "as" makes the sentence perfectly clear to me. 
But I would also avoid to use the term "diagram". Even if we don't understand graphics by this term, I assume that many readers of the standard will do so. 
Thus, "the Conceptual Model is defined as a UML model" would be fine for me.

**Comment by 3DXScape** [comment]
In another SWG I have used the language "The XXXXXXX Logical Model is expressed in the Unified Modelling Language (UML: ISO/IEC 19505-1:2012 Information Technology — Object Management Group Unified Modeling Language)."

But Tatjana's comment is OK for me.

**Comment by cmheazel** [comment]
@3DXScape Let's take this discussion to #162

**Comment by TatjanaKutzner** [comment]
Section 7: This section was added on purpose to provide at least a short and fundamental introduction to the understanding of CityGML, in particular of those concepts that cannot be learned from looking at the UML model and the data dictionary alone. Thus, Section 7 should stay here. A more detailed introduction to CityGML will be provided in the Users Guide.

**Comment by cmheazel** [comment]
All comments from Carls' redline document have been addressed.

**Comment by TatjanaKutzner** [comment]
I reviewed Carls redline document and how the comments have been addressed. In general it looks great. 
However, there are some points that should be changed. I already did so for most of them:

p 6: 
- [x] "This standard defines the open CityGML Conceptual Model Standard for ..." -> "This standard defines the open CityGML Conceptual Model for ..."

p 9: 
- [x] 3D cadastral -> Change back to 3D cadastre. It currently reads as CityGML is for 3D cadastral and other types of navigation. This is not the intention. (This was not a comment from Carl, but was also changed).

p 10:
- [x] technology-specfic -> technology-specific
- [x] nor schema for CityGML 3.0 -> schemas
- [x] Environmental, -> remove line break as this list item and the next one belong together

p 11:
- [ ] The links to the citations of 3D Tiles and 3DPS don't work.

p 23:
- [x] Versioning should be a list item of its own
- [x] "can specify support for a subset of the CityGML modules" -> I prefer to include the word "only" again to emphasise that not all modules always need to be supported.

p 25:
- [x] "from which many subclasses can be created" -> remove "many", it does not always have to be many subclasses that are created
- [x] The sentence "Only top-level features are allowed as direct members of a CityModel object." should be added again, as it is an important aspect of top-level features. Changing "CityModel object" to "city model" should solve the issue from Carl's redline document.

p 36:
- [x] Versioning module: Change list form back to continuous text and provide items as examples. The current list form implies that only these two types of changes can be managed by the Versioning module. However, they are only examples.
- [x] I think the WFS standard is meant here, i.e. "no extension of the OGC Web Feature Service standard is required ...".

p 37:
- [x] "specifying" is not correct here. The Dynamizer does not specify dynamic property values, it simply links the dynamic values to the object attribute.

p 38:
- [ ] "The concept of generic objects and attributes enables the runtime extensions of CityGML applications": This is not clear to me. It implies to me that there are specific runtime extensions that already exist and have already been explained previously in this document. It does not imply to me that CityGML can be extended during runtime. Or is it more common to speak of runtime extension in the English language?

p 50:
- [x] ImplicitGeometry definition: For example -> Examples are (otherwise it's a sentence without a verb)

p 68:
- [x] "in which the timeseries data is included" -> "in which the Dynamizer is included"

p 102:
- [x] with raising of buildings it is meant that the building is extended, e.g. by building another storey on top of the building -> Include the example again and change "raising" to "extension"

p 304:
- [x] ISO 19109 defines rules for creating application schemas in UML and ISO 10103 defines rules for using UML to model geographic information. -> The text should be modified accordingly.

**Comment by TatjanaKutzner** [comment]
Proposed changes which have not been addressed are moved to issue #171
