### ISSUE TITLE
use of attribute roofType whose type is code for AbstractBuilding

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#30]
The feature type AbstractBuilding has an attribute roofType whose type is code.
It might be worth to have a standardised code list for roof types.
In INSPIRE, we used the example given in previous version of CityGML + value ” hyperbolicParabaloidalRoof”
Proposal:  include a standardized code list for roofType (or at least an example).

**Comment by royrathbun** [comment]
OSM has a list of tags for rooftypes at https://wiki.openstreetmap.org/wiki/Simple_3D_buildings.  NSG Registry has a codelist at https://nsgreg.nga.mil/ir/view?i=726717&month=9&day=18&year=2018

**Comment by 3DXScape** [comment]
I think we will need to allow different list for different applications/geographies/cultures.

**Comment by TatjanaKutzner** [comment]
In today's web conference we opted for not providing a standardised code list for roof types, because a) also in CityGML 3.0 it is intended that code lists are defined outside the CityGML specification, and b) roof types vary all over the world and we won't be able to cover all relevant roof types in the code list. However, we will provide an example code list in the specification.

**Comment by TatjanaKutzner** [comment]
Relates to #10
