### ISSUE TITLE
Naming of the classes Room and Storey in the Building module

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#33]
In the _Building_ module, the Room class is simply named _Room_, whereas in the _Bridge_ module the class is named _BridgeRoom_. Should we change the name to _BuildingRoom_, to be consistent in naming? Also, all other classes like Installation, Furniture, etc. have the prefix Building.
In addition, the name of the class _Storey_ should then be changed to _BuildingStorey_ as well.

**Comment by hlg** [comment]
+1 for consistent naming, but I am not sure whether prefixing of class names in addition to the module namespace prefixes is necessary.

**Comment by clausnagel** [comment]
Agree with @hlg that the module namespaces should be sufficient. So I think we should use _Room_ in all modules rather than _BuildingRoom_ and _BridgeRoom_. If possible, common concepts could even be drawn to the _Construction_ base module.

**Comment by 3DXScape** [comment]
Do we have an accepted proposal?

**Comment by 3DXScape** [comment]
I am closing this issue with the resolution that the classes should have the name "Room" and that the module namespace is adequate to disambiguate the use of the similar (same?) concept in different contexts.

**Comment by clausnagel** [comment]
Reopening since the proposal has not been considered in the latest editor‘s draft.

**Comment by clausnagel** [comment]
We discussed different scenarios in the modelling sub-group. There was agreement that a consistent naming scheme should be applied to all modules. 

Using the same class names like _Room_ or _Installation_ in different modules is technically possible since the classes live in different namespaces. However, it also causes confusion when referencing the concepts and might impede implementations. Drawing classes with identical meaning to a common base module is also a valid option. But in this case, ADE extensions could only be applied on the level of the base module. For instance, it would not be possible anymore to inject specific ADE attributes only to building rooms but not to bridge rooms. This was considered a major drawback, not only because it is possible in CityGML 2.0.

The consensus in the group was therefore that class names should not be identical over modules. To fix the issue, it is proposed to use the module name as prefix wherever required. So, in answer to the initial post, the classes _Room_, _Installation_, _Furniture_ etc. in the building module should be renamed to _BuildingRoom_, _BuildingInstallation_ and so on.

**Comment by hlg** [comment]
The original issue also mentioned `Storey`, which only exists in the building module, as far as I could see. Should the prefix convention also extend to all class names that appear only in one module or be restricted to those that appear in more than one module?

**Comment by 3DXScape** [comment]
My opinion is that the principle is "identical names for different concepts should not be used within (obvious) or across modules".  This is in addition to the possibility of using namespace names to disambiguate. 
So if a name only appears in one module, it need not be prefixed. If a new module is created or existing module is changed, then all existing modules should be examined to identify possible name clashes. Prefix(es) or name changes should be used to eliminate the conflict(s).
If the names are truly identifying the same concept, then an effort should be made to define the concept once in a core module.

**Comment by clausnagel** [comment]
Agree with @3DXScape that prefixing should not be required if a name only occurs in a single module.

Defining an overarching concept in a base/core module makes sense. Still we need an instance (with prefixed name) in every submodule to enable ADE attribute injections.

**Comment by hlg** [comment]
This is, what I was assuming too. Just wanted to clarify because the summary was not clear about this aspect of the original isuue.

**Comment by TatjanaKutzner** [comment]
This issue will be closed, as in the webconference on 21 February 2019 it was decided to rename _Room_ to _BuildingRoom_, but to keep the name _Storey_ as it is, based on above discussion that prefixes are only to be used when the name appears in more than one module.
