### ISSUE TITLE
Objectified relations

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#4]
Are the association classes for relations (objectified relations in Core module / Space Relations) just there for adding type information to the relation?  Or are there any plans to attach more information to these relations, e.g. associations to parts of the geometries of the related features, so that e.g. a touching relation between a room and a construction element would be associated with the respective thematic surface? Again, this is an idea taken from IFC, which must probably not be reproduced in CityGML. Just want to confirm.

**Comment by hlg** [comment]
I had made a list of `IfcRelationship` sub types in IFC4 Add2 TC1, which have additional attributes (beyond the relating and related entities) for a [recent publication](http://doi.org/10.1201/9780429506215-53). I found a list of 15 such `IfcRelationship` sub types with a total of 27 additional attributes, one of which is mandatory.

Following up on the working group discussion, I have reviewed them now in order to find an example where it would be beneficial to add an additional attribute to a generic relation. To the best of my judgement, these relationship types fall in one of the following categories:

1. Relationship types that are irrelevant for GIS use cases and will probably not appear in CityGML because
    - one of the related entity types is not specific to the geospatial domain or
     - the relation itself is really specific to CAD or structural analysis.
2. Relationship types that can be reflected with standardized CityGML 3 object and property types and don't need any generic relation at all.
3. Relationship types where the generic relation with an extendable relationship type codelist  is sufficient.

There was no "reminder" category that would make a case for additional attributes.

I found one particularly interesting case though, which is [IfcRelAssignsToGroupByFactor](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/ifcrelassignstogroupbyfactor.htm). Here we have a relation between an object and a group enhanced with a weighting attribute. You may want to wish for a respective weighting attribute in CityGML as well. But a generic relation would not help here, because there is already the standardized `groupMember` property in CityGML 3, which covers the same semantics and should most likely be used. So in this case, an ADE would be inevitable anyway,

**Comment by TatjanaKutzner** [comment]
At the last web conference on 18 April 2019 we discussed whether we should allow relationships to be treated as objects with identifiers so that they can be queried from a Web Feature Service. 
We think this is not required, since all city objects are derived from the class AbstractCityObject. A query can be sent to the Web Feature Service to search for AbstractCityObject in combination with a specific type of relationship.

We also discussed whether it would be useful to allow generic attributes with relationships.
We decided to leave the object relation modelling currently as it is, but we will bring up the topic to the SWG, to get further opinion on whether relationships with generic attributes would be useful.

In addition, we will look for examples from IFC, as IFC makes use of relationships with attributes between objects (see comment above). A mapping from IFC to CityGML would then be more complete.
