### ISSUE TITLE
Engineering CRS

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#45]
The CityGML 2 specification allowed to define an engineering CRS as CityModel metadata property (Example G.9, pp. 301, [Building_LOD1-LocalEngineeringCRS.gml](http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD1-LocalEngineeringCRS.gml)). Will this still be possible in CityGML 3?

**Comment by TatjanaKutzner** [comment]
We discussed this issue at the web conference on 17 May 2019.

We did not come to a conclusion whether this will still be possible, because GML 3 does not provide the metadata property any more. We will ask Clemens on this issue.

Furthermore, we are not sure if any software exists that could handle engineering CRS. Thus, is it in that case still necessary to include engineering CRS?

We will discuss this issue at the next OGC meeting in Leuven, June 2019.

**Comment by hlg** [comment]
Engineering CRS would be helpful for BIM-GIS integration. I believe that geometry with higher levels of detail such as the interior of buildings which is originally given in a geo-referenced cartesian coordinate system should not be converted to geographic coordinate systems and could cause integration problems.

If there are externally defined canonical engineering CRS with different units of measurement, then it  would not be necessary to define these CRS inline, but reference by URI would be sufficent.

**Comment by heidivanparys** [comment]
> We did not come to a conclusion whether this will still be possible, because GML 3 does not provide the metadata property any more.

In order to do this with the latest GML version, a property "engineeringCRS" should be added to CityModel, with the corresponding type from ISO 19111, and the tagged value "isMetadata" on this property should be set to "true".

![image](https://user-images.githubusercontent.com/11427611/60709114-f8dbf000-9f0f-11e9-9dad-635804cd768c.png)

![image](https://user-images.githubusercontent.com/11427611/60709125-fe393a80-9f0f-11e9-9fc8-c229fce46c75.png)

![image](https://user-images.githubusercontent.com/11427611/60709130-01ccc180-9f10-11e9-9782-79128563724d.png)

**Comment by TatjanaKutzner** [comment]
In the modelling subgroup meeting on 21 October 2019 we agreed on implementing this issue in the way suggested by Heidi.
