### ISSUE TITLE
Deriving ADE classes from _Feature

### ISSUE THREAD

**Issue by gioagu** [opengeospatial/CityGML-3.0CM#61]
When designing an ADE it might make sense to derive some classes directly from _Feature instead of  _CityObject.

Example: see AbstractConstruction in the Energy ADE (see: https://git.rwth-aachen.de/energyade/citygml-energy/blob/v1.0/doc/UML-Diagrams_Energy-ADE.pdf)

As a CityModel is derived from _FeatureCollection, it also inherits relation _featureMember, hence it should be allowed to have _Feature-derived classes and not only _CityObject-derived ones.

In the specific case: the idea is to have the Construction-Objects at _root_ level in the CityGML document, and to reference them via Xlinks from all related objects.

Could the specifications state a bit more explicitly whether this is originally intended/allowed or not?

Thanks for your support!

**Comment by TatjanaKutzner** [comment]
We confirmed in the web conference on 17 May 2019 that it is allowed to derive classes directly from __Feature_ and we will describe this more explicitly in the CityGML 3 specification.

However, _CityModel_ is no longer derived from __FeatureCollection_ in CityGML 3; thus, the relation _featureMember_ does not exist any more. Only relations, that are explicitly defined in the data model can be used, currently these relations are _cityObjectMember_, _appearanceMember_, _versionMember_, and _versionTransitionMember_. 
To solve this, we discussed to complement the UML model by a class _AbstractFeature_ as shown in this figure:
![#61](https://user-images.githubusercontent.com/5949401/58665493-4a9dc300-8331-11e9-841c-dfa091be671f.jpg)
The ADE classes can then directly be derived from the class _AbstractFeature_ and be included as _featureMember_ objects in the CityGML document.

**Comment by TatjanaKutzner** [comment]
ISO 19109 defines a class _AnyFeature_ that is an instance of the metaclass _FeatureType_. The standard specifies that all classes in a UML application schema with the stereotype `<<FeatureType>>` shall be derived from the class _AnyFeature_. 

This approach was used in the LandInfra UML model. 

Instead of defining the class _AbstractFeature_ as discussed above, I also used now the class _AnyFeature_ as superclass in the CityGML UML model, see commit 2cb5453:
![grafik](https://user-images.githubusercontent.com/5949401/58668462-49709400-8339-11e9-8d1f-73606991fd16.png)

The encoding with ShapeChange works without problems. An additional relation _featureMember_ is added in the XML schema document.

What are your opinions on that?
