### ISSUE TITLE
Generics module - Decision required on which alternative to choose

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#65]
The UML model currently still contains two different alternatives for modelling the Generics module.
We still have to decide which alternative to choose.
Currently, the encoding makes use of the alternative shown in the PDF on page 16.

**Comment by clausnagel** [comment]
In general, I prefer the first alternative on p. 16 of the PDF because it’s simpler and more consistent with the other modules.

However, I think it is not a good idea to completely remove the `GenericCityObject` feature type. It is widely used in existing CityGML 2 datasets.

I guess that the current use of `GenericCityObject` is almost always to represent an “occupied space”. So I propose two alternatives:

1. Rename the `GenericOccupiedSpace` to `GenericCityObject`.
2. Add `GenericCityObject` as additional feature type that is also derived from `AbstractOccupiedSpace`.

**Comment by clausnagel** [comment]
And should GenericThematicSurface really be a top-level feature type?

**Comment by clausnagel** [comment]
The issue was discussed in today's modelling subgroup meeting, which resulted in the following proposal:

1. `GenericThematicSurface` should remain a top-level feature because there are already examples of other top-level thematic surfaces in CityGML 3.0 such as `LandUse` or terrain surfaces.
2. There was consensus in the group that the first alternative on p. 16 is much more consistent with the rest of the conceptual model than the second alternative. This is because all "has-a" assocations from a feature type to a space class have been removed from the model - instead, the feature types are now derived from the space classes. However, the second proposal requires to use "has-a" associations to spaces and thus would be inconsistent.

As a consequence, `GenericCityObject` would be removed in CityGML 3.0 in favor of `GenericOccupiedSpace`, `GenericUnoccupiedSpace`, `GenericLogicalSpace` and `GenericThematicSurface`. 

Since not all generic city objects used in current CityGML 2.0 datasets necessarily represent occupied spaces, the group agreed that adding an additional `GenericCityObject` derived from `AbstractOccupiedSpace` or even renaming `GenericOccupiedSpace` to `GenericCityObject` as proposed above wouldn't cover all cases and thus should not be implemented.
