### ISSUE TITLE
Questions about some class relationships 

### ISSUE THREAD

**Issue by yaozhihang** [opengeospatial/CityGML-3.0CM#70]
In the current UML-Diagrams some relationships e.g. the relationship between _AbstractBuilding_ and _BuildingFurniture_,  _AbstractBuilding_ and _BuildingInstallation_, are modeled as `Aggregation` with a multiplicity of M:N. Should 1:N `Composition` be used instead?

**Comment by thomashkolbe** [comment]
These relationships are M:N and modeled as an `Aggregation`, because such objects can be so large or placed in such a way in the real world that they in fact belong to more than just one building or building part. For example, a pipe or a gutter can extend over multiple building parts. We have also collected real world examples, where a number of buildings have one single big shading installation arching over all buildings. The same is true for furniture. If you have two building parts that are connected by an opening, there can be some furniture standing half in one building part and half in the other (e.g. a large bench or cupboard).

**Comment by yaozhihang** [comment]
@thomashkolbe Thanks for the clear explanation. Right, `Aggregation` looks better and is compatible with these kinds of specific realworld scenarios.
