### ISSUE TITLE
Relation between AbstractBuilding and AbstractBuildingSubdivision

### ISSUE THREAD

**Issue by frisopenninga** [opengeospatial/CityGML-3.0CM#71]
The relation is now modelled as a decomposition, which is not the case in the INSPIRE model. I think the decomposition is to strict. In the Dutch case, the BAG (Buildings and Adresses Registration) allows a BuildingUnit to be in more than one Building / BuildingPart. See https://bagviewer.kadaster.nl/lvbag/bag-viewer/#?searchQuery=0202010000423721&geometry.x=190780.861&geometry.y=443841.456&zoomlevel=6&objectId=0202010000423721&detailsObjectId=0202010000423721 . I know it is in Dutch, but you see a case in which one 'Verblijfsobject' (INSPIRE BuildingUnit) is part of three 'Panden' (BuildingParts). In this case, it looks like old buildings that have been internally connected by doors in walls in order to create one large store. 

The question is whether you want an administrative subdivision (BuildingUnit) to be defined equally strict as a physical subdivision (BuildingPart). I do understand the decomposition in the latter case, not in the former case. A m:n assocation might fit better with real life applications.

**Comment by thomashkolbe** [comment]
Good point! I agree, that it should be possible to relate a `BuildingUnit` to more than one `BuildingPart`. Therefore, we should replace the composition relationship to `AbstractBuildingSubdivision` by an aggregation relationship with a multiplicity of *. This should not cause bigger implementation efforts, because also the relationships to other building entities like `BuildingInstallation` and `BuildingRoom` are already modeled in that way.
