### ISSUE TITLE
Use of TopLevelFeatureType stereotype for subclasses

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#81]
In the `Transportation` module, the feature class `TransportationComplex` is correctly marked as top-level feature by using the stereotype `<<TopLevelFeatureType>>`. Its subclasses `Road`, `Railway`, etc. are however tagged as `<<FeatureType>>`. 

I think `<<TopLevelFeatureType>>` should also be used for the subclasses, shouldn't it? If so, then this has also to be corrected in other modules (e.g. for buildings).

**Comment by TatjanaKutzner** [comment]
Yes, I think it makes sense to use the stereotype `<<TopLevelFeatureType>>`also for the subclasses of `TransportationComplex`. 

However, it is different for the `Building` module. Here the class `Building` has the stereotype `<<TopLevelFeatureType>>` and not the superclass `AbstractBuilding`, because we only want the class `Building` to be a top level feature type. We do not want the class `BuildingPart` to be a top level feature type as well. The same applies to the modules `Bridge` and `Tunnel`.

We could assign the stereotype to the class `AbstractVegetationObject`, as both subclasses already have the stereotype.
But: Should the stereotype also be assigned to abstract classes or only to concrete classes?

For all other modules it looks correct already.

**Comment by TatjanaKutzner** [comment]
Will be discussed together with issue #64.

**Comment by TatjanaKutzner** [comment]
The issue has been solved. The subclasses `Road`, `Railway`, etc. have now the stereotype `<<TopLevelFeatureType>>`,  while their abstract superclass `AbstractTransportationSpace` has the stereotype `<<FeatureType>>`. Only concrete classes are to be marked as top level feature types.
