### ISSUE TITLE
Purpose of MultiCurve representation of spaces?

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#84]
What is the purpose of the MultiCurve representation of `AbstractSpace` in LOD 2 and 3? How would the boundary of such a representation be expressed using `AbstractThematicSurface` (note that `AbstractThematicSurface` does not have a point representation)?

Is this meant to model curve-like attachments of a space (like the antennas of a building)? Then I would prefer a dedicated feature type for such attachments with an appropriate geometry representation. And the MultiCurve representations should be removed from `AbstractSpace`.

**Comment by thomashkolbe** [comment]
The purpose of the `MultiCurve` representation of `AbstractSpace` is not exactly as you assume in the second part of your comment. It is meant to model city objects whose geometries typically are geometrically abstracted by curves. Examples would be `BuildingInstallations` like an antenna of a building or a tree trunk.

Since these things also occupy space in the real world (even if they might be very thin), they need to be semantically modeled as Spaces. However, an appropriate geometry representation could be just a `Curve` or `MultiCurve`. 

I would agree, that if somebody wants to represent an antenna on a building, it should not just be geometrically added as an additional Curve to the geometric representation of the building space, but should be added as a dedicated `BuildingInstallation` feature (which then only uses the Curve representation).

It is true that for a `Curve` representation no dedicated boundary (like a `Surface` or `Point`) can be represented. But this is also true for the LOD0 representation of a Space, which could be just a single `Point` (that also has no boundary).
