### ISSUE TITLE
Fix relation between AbstractSpaces and AbstractThemanticSurfaces

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#85]
According to the Core module, `AbstractSpace` has a general zero-to-many relationship to `AbstractThematicSurface` that is navigable in both directions. In many but not all extension modules this relationship is restricted. For instance, an `AbstractConstruction` can only be bounded by `AbstractConstructionSurface` and the association is only navigable in this direction.

However, these restrictions are not very consistent. For example, `BuildingRoom` is directly derived from `AbstractUnoccupiedSpace`. Does this mean, that the boundary relationship is not restricted to `AbstractConstructionSurface` but that it can be bounded by every subclass of `AbstractThematicSurface` (note that this includes, for instance, `LandUse` and `TINRelief`)? This wouldn't really make sense, would it?

The relationsship between a space and its allowed thematic boundary surfaces should be much clearer and explicit. Maybe the general relationship in the Core module should be dropped and only be defined in the extension modules.

I am also not really convinced about the way `ClosureSurface` is used. It is defined in the Core module as subclass of `AbstractThematicSurface`. But since the boundary relation for `AbstractConstruction` is restricted to `AbstractConstructionSurface` it cannot be used directly. Therefore, a "has a" relation from `AbstractConstructionSurface` to `ClosureSurface` has been introduced. But this means, you cannot model a `ClosureSurface` on its own for construction spaces, but it always requires an embracing instance of a construction surface like roof or wall surface. Again, imho, this does not really make sense and is very different to CityGML 2.0

**Comment by clausnagel** [comment]
Just to have more examples, here is a non-exhaustive list of spaces whose boundary relationship is not restricted and which consequently could be bounded by any subclass of `AbstractThematicSurface` such as `LandUse` or `TINRelief`:

* `AbstractConstructiveElement`
* `AbstractFillingElement`
* `AbstractFurniture`
* `AbstractInstallation`
* `AbstractBuildingSubdivision`
* `BuildingUnit`
* ...

Actually, the list of spaces whose boundary relation is reasonably restricted is much shorter.

**Comment by TatjanaKutzner** [comment]
This issue was discussed at the SWG meeting in Banff, September 2019. Two options were presented to resolve the problem: 
1. By providing OCL constraints in the UML model, the thematic surfaces that are allowed for a specific space (e.g. `BuildingRoom`) can be specified explicitly. The disadvantage with this solution is, however, that the space cannot be bounded by thematic surfaces that are defined as part of an ADE. The space can only be bounded by those surfaces that are now defined in the OCL constraint, it is not possible to include future thematic surfaces defined by an ADE in the OCL constraint now.
2. Alternatively, the allowed surfaces can be specified as normative requirement in the Conceptual Model specification in textual form. Here it can also be defined that the normative requirement is valid for surfaces defined within ADEs as well.

Due to the disadvantage of option 1 we discussed at the modelling subgroup meeting on 18 October 2019 that we would like to proceed with option 2.
