### ISSUE TITLE
Relation and role names; reading order

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#87]
I would like to see relations having both a name and a reading order in the model, as that would help a lot in understanding the meaning of the relations, especially given the convention decided on in #55 .

I would like to see verbs as relation names and (singular) nouns as role names.

An example:
![image](https://user-images.githubusercontent.com/11427611/64408253-8fe73480-d086-11e9-831b-d1790affc8ad.png)

An abstract space may have boundaries. ✔️
An abstract thematic surface may have bounds. ❌
An abstract thematic surface ?? an abstract space. ❌

Modified example:
![image](https://user-images.githubusercontent.com/11427611/64408224-83fb7280-d086-11e9-96a7-7041e169cbd4.png)

An abstract space may have boundaries. ✔️
An abstract thematic surface may have bounded spaces. ✔️
An abstract thematic surface bounds an abstract space. ✔️

**Comment by TatjanaKutzner** [comment]
In the web conference on 18 October 2019 we discussed that we prefer not to provide relation names and reading orders in the UML model for several reasons:

- We only have uni-directional associations in the UML model, thus, the reading order is already provided by the direction of the association. The example from above is now modelled in this way: 
![grafik](https://user-images.githubusercontent.com/5949401/67210709-d7006d80-f419-11e9-8d0b-673df9e8a347.png)
- In CityGML 2.0 we only used role names and, thus, would like to stick to this in CityGML 3.0. Also for encoding the role names are required.
- Introducing relation names in addition to role names would make the UML model less clearly readable, due to the many associations which all would need to be complemented with a relation name.
